### ISSUE TITLE
First Year Competitive Programming Classes urls don't work

### ISSUE THREAD

**Issue by DNA5769** [CC-MNNIT/2020-21-Classes#55]
![image](https://user-images.githubusercontent.com/40732639/129965359-69e941cc-4669-4dc0-904a-fbe0a0bd9329.png)

The links in the image above redirect to a 404 url

![image](https://user-images.githubusercontent.com/40732639/129965644-8f7b7714-9496-47b5-8798-a53b582d61ce.png)

## Fix
The above links redirect to the following urls respectively
- [https://cc-mnnit.github.io/2020-21-Classes/First_Year_Competitive_Programming](https://cc-mnnit.github.io/2020-21-Classes/First_Year_Competitive_Programming)
- [https://cc-mnnit.github.io/2020-21-Classes/First_Year_Competitive_Programming/07_02_2021_Class_1](https://cc-mnnit.github.io/2020-21-Classes/First_Year_Competitive_Programming/07_02_2021_Class_1)
- [https://cc-mnnit.github.io/2020-21-Classes/First_Year_Competitive_Programming/13_02_2021_Class_2](https://cc-mnnit.github.io/2020-21-Classes/First_Year_Competitive_Programming/13_02_2021_Class_2)
- [https://cc-mnnit.github.io/2020-21-Classes/First_Year_Competitive_Programming/14_02_2021_Class_3](https://cc-mnnit.github.io/2020-21-Classes/First_Year_Competitive_Programming/14_02_2021_Class_3)

As you can see all of these are invalids urls and should be replaced with their proper urls
- [https://cc-mnnit.github.io/2020-21-Classes/Freshers/First_Year_Competitive_Programming](https://cc-mnnit.github.io/2020-21-Classes/Freshers/First_Year_Competitive_Programming)
- [https://cc-mnnit.github.io/2020-21-Classes/Freshers/First_Year_Competitive_Programming/07_02_2021_Class_1](https://cc-mnnit.github.io/2020-21-Classes/Freshers/First_Year_Competitive_Programming/07_02_2021_Class_1)
- [https://cc-mnnit.github.io/2020-21-Classes/Freshers/First_Year_Competitive_Programming/13_02_2021_Class_2](https://cc-mnnit.github.io/2020-21-Classes/Freshers/First_Year_Competitive_Programming/13_02_2021_Class_2)
- [https://cc-mnnit.github.io/2020-21-Classes/Freshers/First_Year_Competitive_Programming/14_02_2021_Class_3](https://cc-mnnit.github.io/2020-21-Classes/Freshers/First_Year_Competitive_Programming/14_02_2021_Class_3)

**Comment by nisiddharth** [comment]
#56

**Comment by sidhantagar** [comment]
All the links in the readme have been rectified. Thank you!
